- lib/compare.js
* use explicit names for boolean values (array1 => isArray1)
* 'continue' -> and clause
* if () return true/false -> return expression
Probably will fail CI without https://github.com/metarhia/metatests/pull/87
> Slightly simplify and refactor compare.js

- lib/compare.js
- lib/report.js
- test/compare.js
* compare 'function' with toString in equal and strictEqual
* add special reported case to output them properly
* add tests
> Implement simple function comparison via toString

- lib/runner.js
metatests.runner.instance.options.runTodo = true ->
metatests.runner.instance.runTodo(true)
> Add setter for running 'todo' in Runner

- lib/runner.js
- lib/test.js
- test/imperative.js
- test/runner.js
* do not count falied todo tests as runner failure
* do not count failed todo subtest as parent failure
> Fix todo test reporting

- lib/imperative-test.js
- test/exit-code.js
- test/imperative.js
Refs: https://github.com/metarhia/metatests/issues/72#issuecomment-419206624
PR-URL: https://github.com/metarhia/metatests/pull/126
> Make fail only report 'failed' not end test

- lib/report.js
- lib/test.js
- test/imperative.js
> Add filename metadata and print it

- lib/imperative-test.js
- test/plan-mustcall.js
- test/unit/imperative._passCheck-exactly-planned.js
- test/unit/imperative._passCheck.js
Refs: https://github.com/metarhia/metasync/pull/421
> Fix test.plan + test.mustCall interoperability

- lib/imperative-test.js
- lib/report.js
* filepath property is present in test.metadata.filepath
* irrelevant TODO in TapReporter.error
> Remove outdated TODOs

- lib/imperative-test.js
- test/test-rejects-test.js
- test/test-resolves-test.js
These will allow to simplify interaction with multiple checks with
promises.
> Implement test.resolves, test.rejects utilities

- lib/imperative-test.js
- lib/test.js
- test/imperative.js
- test/unit/imperative.end-before-subtests.js
- test/unit/imperative.run-subtests.js
- test/unit/imperative.run.js
- test/unit/test._end-done-successful-last-result.js
See separate commits for description.
> Few internal fixes

- lib/imperative-test.js
- test/test-rejects-test.js
- test/test-resolves-test.js
Edit: see commit for proper description.
> Handle test.resolves(promise) specially

- bin/cli.js
If there are failures the process will now exit immediately, otherwise
wait for normal process finish.
> Remove waiting timeout from CLI

- lib/imperative-test.js
- test/plan-timeout-result.js
- test/test-rejects-test.js
- test/test-resolves-test.js
- test/unit/imperative._end.js
- test/unit/imperative._passCheck-exactly-planned.js
- test/unit/imperative._passCheck.js
- test/unit/imperative.end-before-subtests.js
- test/unit/imperative.end-planned.js
- test/unit/imperative.endAfterSubtests.js
- test/unit/imperative.exceed-timeout-timer.js
/cc @nechaido 
This now contains a few more commits.
> Extract _record/_recordPass, Explicitly record 'rejects'/'resolves', refactor subtest record, increase stack trace

- test/plan-timeout-result.js
Fixes: https://github.com/metarhia/metatests/issues/205
> Increase plan test timeout to reduce race condition

- test/imperative.js
- test/unit/imperative.dependent-failure.js
- test/unit/imperative.run-subtests.js
Extracted from https://github.com/metarhia/metatests/pull/218.
> Fix tests and race conds

- lib/imperative-test.js
- lib/utils.js
- test/fixtures/imperative.test-dependent.js
- test/fixtures/imperative.test-with-runner.js
- test/unit/imperative.test-independent.js
- test/unit/imperative.test.js
Extracted from #218 commits related to Test.
> Fix imperative test cross os and harder warning tests

- CHANGELOG.md
- bin/cli.js
- package.json
Extracted from https://github.com/metarhia/metatests/pull/218 commits related to CLI.
> Fix cli cross os

- CHANGELOG.md
- README.md
- lib/imperative-test.js
- test/imperative-is.js
~~Based on https://github.com/metarhia/metatests/pull/220~~
>  feat: implement test#is, test#isArray, test#isBufer

- README.md
- benchmarks/README.md
- benchmarks/compare.R
- benchmarks/createObject.js
- benchmarks/example/benchmark.js
- benchmarks/example/create.js
- benchmarks/setVsArray.js
- benchmarks/stringJoin.js
- lib/speed.js
- metatests.js
- test/fixtures/speed.js
- test/measure.js
- test/speed.js
- test/test-unhandled-exceptions.js
- test/unit/imperative.run-subtests.js
/cc @belochub @tshemsedinov @nechaido 
See separate commits for better understanding.
Also, can someone help me with the wording in the benchmark readme section `### Typical usage pattern`?
> Improve microbenchmarks

- .metadocrc
- README.md
- lib/imperative-test.js
~~Fails tests, for now, looks like metadoc for some reason doesn't add custom links to the output.~~
Looks like I had a stale version of metadoc installed locally, all fixed.
> feat: add documentation for ImperativeTest

- lib/imperative-test.js
- test/unit/imperative.test-null-options.js
> fix: improve imperative test function to receive options as null
